spring.application.name=ensino

spring.datasource.url=jdbc:mysql://localhost:3306/ensino
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true
